# Generated by Django 5.1.4 on 2025-01-17 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('today_completed', models.IntegerField(default=0)),
                ('today_incomplete', models.IntegerField(default=0)),
                ('longgoal_complete', models.IntegerField(default=0)),
                ('longgoal_incomplete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('context', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(default='2025-1-1')),
                ('completed', models.BooleanField(default=False)),
                ('is_long_term_goal', models.BooleanField(default=False)),
            ],
        ),
    ]
