# Generated by Django 5.1.4 on 2025-01-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journalapp', '0003_journal_catgories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='catgories',
            field=models.CharField(choices=[('Personal', 'PERSONAL'), ('Information', 'Information'), ('Thoughts', 'THOUGHTS'), ('Tasks', 'TASKS'), ('Notes', 'NOTES'), ('News', 'NEWS'), ('Random', 'RANDOM'), ('Work', 'WORK'), ('Study', 'STUDY'), ('Finance', 'FINANCE'), ('Travel', 'TRAVEL'), ('Recipes', 'RECIPES'), ('Projects', 'PROJECTS'), ('Ideas', 'IDEAS'), ('Health', 'HEALTH'), ('Reminders', 'REMINDERS'), ('Polity', 'POLITY'), ('Economy', 'ECONOMY'), ('Geography', 'GEOGRAPHY'), ('History', 'HISTORY'), ('Science & Tech', 'SCIENCE & TECH'), ('Environment', 'ENVIRONMENT'), ('Current Affairs', 'CURRENT AFFAIRS'), ('Unmarked', 'UNMARKED')], default='Unmarked', max_length=30),
        ),
    ]
