# Generated by Django 5.1.4 on 2025-01-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journalapp', '0004_alter_journal_catgories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='catgories',
        ),
        migrations.AddField(
            model_name='journal',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Information', 'Information'), ('Thoughts', 'Thoughts'), ('Tasks', 'Tasks'), ('Notes', 'Notes'), ('News', 'News'), ('Random', 'Random'), ('Work', 'Work'), ('Study', 'Study'), ('Finance', 'Finance'), ('Travel', 'Travel'), ('Recipes', 'Recipes'), ('Projects', 'Projects'), ('Ideas', 'Ideas'), ('Health', 'Health'), ('Reminders', 'Reminders'), ('Polity', 'Polity'), ('Economy', 'Economy'), ('Geography', 'Geography'), ('History', 'History'), ('Science & Tech', 'Science & Tech'), ('Environment', 'Environment'), ('Current Affairs', 'Current Affairs'), ('Unmarked', 'Unmarked')], default='Unmarked', max_length=30),
        ),
    ]
