# Generated by Django 5.1.5 on 2025-02-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journalapp', '0006_journal_mood_alter_journal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Gratitude', 'Gratitude'), ('Insight', 'Insight'), ('Reflection', 'Reflection'), ('Mindbyte', 'Mindbyte'), ('Mathematics', 'Mathematics'), ('Astrology', 'Astrology'), ('Machine_Learning', 'Machine_Learning'), ('Programming', 'Programming'), ('Literature', 'Literature'), ('Poetry', 'Poetry'), ('Cinema', 'Cinema'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion'), ('Information', 'Information'), ('Thoughts', 'Thoughts'), ('Tasks', 'Tasks'), ('Notes', 'Notes'), ('News', 'News'), ('Random', 'Random'), ('Physics', 'Physics'), ('Work', 'Work'), ('Study', 'Study'), ('Finance', 'Finance'), ('Travel', 'Travel'), ('Recipes', 'Recipes'), ('Projects', 'Projects'), ('Ideas', 'Ideas'), ('Health', 'Health'), ('Reminders', 'Reminders'), ('Polity', 'Polity'), ('Django', 'Django'), ('Economy', 'Economy'), ('Culture', 'Culture'), ('F_E_Programming', 'F_E_Programming'), ('CPP Language', 'CPP Language'), ('Geography', 'Geography'), ('Java', 'Java'), ('Python', 'Python'), ('History', 'History'), ('Art', 'Art'), ('Music', 'Music'), ('Science & Tech', 'Science & Tech'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Statistics', 'Statistics'), ('Environment', 'Environment'), ('Current Affairs', 'Current Affairs'), ('Unmarked', 'Unmarked')], default='Unmarked', max_length=30),
        ),
    ]
